version: '3.8'

services:
  php-apache:
    image: php:8.0-apache
    container_name: php-apache
    platform: linux/amd64  # Pour forcer l'image à utiliser amd64
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql:8  # Version compatible avec arm64
    container_name: mysql
    platform: linux/amd64  # Forcer l'usage de l'architecture amd64 si nécessaire
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    platform: linux/amd64
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  composer:
    image: composer
    container_name: composer
    platform: linux/amd64
    volumes:
      - ./html:/app
    networks:
      - mynetwork
    working_dir: /app
    entrypoint: ["composer"]

networks:
  mynetwork:
    driver: bridge
