services:
  php-apache:
    image: php:8.0-apache
    container_name: php-apache
    platform: linux/amd64
    ports:
      - "3001:80"
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/docker-php-mysql-apache-mongodb/html:/var/www/html
      - /Applications/XAMPP/xamppfiles/htdocs/docker-php-mysql-apache-mongodb/html/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      - mynetwork


  mysql:
    image: mysql:8
    container_name: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Emile1-Gosh@
      MYSQL_DATABASE: Arcadia
      MYSQL_USER: Arcajosé
      MYSQL_PASSWORD: Emile1-Gosh@
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork

  composer:
    image: composer
    container_name: composer
    platform: linux/amd64
    volumes:
      - ./html:/app
    networks:
      - mynetwork
    working_dir: /app
    entrypoint: ["composer"]

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:
  mongodata:
